#pragma once

#include <stdio.h>

typedef enum {
	SUCCESS = 0,
	FAIL,
	ERROR_GLFW_WINDOW_CREATION,
	ERROR_VULKAN_INSTANCE_CREATION,
	ERROR_VULKAN_EXTENSIONS_NOT_SUPPORTED,
	ERROR_VULKAN_VALIDATION_LAYERS_NOT_SUPPORTED,
	ERROR_VULKAN_ERROR_CALLBACK_CREATION,
	ERROR_VULKAN_NO_PHYSICAL_DEVICE_SUPPORTED,
	ERROR_VULKAN_NO_SUITABLE_GPU,
	ERROR_VULKAN_LOGICAL_DEVICE_CREATION,
	ERROR_VULKAN_SURFACE_CREATION,
	ERROR_VULKAN_SWAPCHAIN_CREATION,
	ERROR_VULKAN_SWAPCHAIN_ACQUIRE_IMAGE,
	ERROR_VULKAN_SWAPCHAIN_PRESENT_IMAGE,
	ERROR_VULKAN_IMAGE_VIEW_CREATION,
	ERROR_VULKAN_SHADER_SRC_LOADING,
	ERROR_VULKAN_SHADER_MODULE_CREATION,
	ERROR_VULKAN_RENDERPASS_CREATION,
	ERROR_VULKAN_PIPELINE_LAYOUT_CREATION,
	ERROR_VULKAN_GRAPHICS_PIPELINE_CREATION,
	ERROR_VULKAN_FRAME_BUFFER_CREATION,
	ERROR_VULKAN_COMMAND_POOL_CREATION,
	ERROR_VULKAN_COMMAND_BUFFER_CREATION,
	ERROR_VULKAN_BEGIN_COMMAND_RECORD,
	ERROR_VULKAN_COMMAND_BUFFER_RECORD,
	ERROR_VULKAN_SYNC_OBJECTS_CREATION,
	ERROR_VULKAN_DRAW_COMMAND_SUBMIT
} State;

void printState(State s);

#define CHECK_STATE(state) do {         \
        if (state != SUCCESS) {         \
                printState(state);      \
                return state;           \
        }                               \
} while(0)
