#pragma once

typedef enum {
	SUCCESS = 0,
	FAIL,
	ERROR_GLFW_WINDOW_CREATION,
	ERROR_VULKAN_INSTANCE_CREATION,
	ERROR_VULKAN_EXTENSIONS_NOT_SUPPORTED,
	ERROR_VULKAN_VALIDATION_LAYERS_NOT_SUPPORTED,
	ERROR_VULKAN_ERROR_CALLBACK_CREATION
} State;
